import {AppRegistry} from 'react-native';
// import  welcome from './01_flex/flex1';
// import  welcome from './01_flex/flex2';
// import  welcome from './02_fetch/fetch1';
// import  welcome from './03_library/tabNavi';
// import  welcome from './03_library/tabNavTop';
// import  welcome from './03_library/banner';
// import  welcome from './03_library/banner2';
// import  welcome from './03_library/banner3';
// import  welcome from './03_library/banner4';
// import  welcome from './04_framework/ele-button';
// import  welcome from './04_framework/ele-heading';
// import  welcome from './04_framework/ele-avatar';
// import  welcome from './05_scroll/scroll1';
// import  welcome from './05_scroll/scroll2';
// import welcome from './period_1/scrollView/listView1';
// import welcome from './period_1/scrollView/listView2';
// import welcome from './period_1/listView/listView3';
// import welcome from './period_1/BasicComponent/button';
// import welcome from './period_1/BasicComponent/navigator';
// import welcome from './period_1/BasicComponent/back';
// import welcome from './period_2/TextInput';
// import welcome from './period_2/TextInput2';
import welcome from './period_2/reactNativeStorage';

AppRegistry.registerComponent('app', () => welcome);